[project]
name = 'Blockchain-Based-Specialized-Agricultural-Water-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.efficient-improvement]
path = 'contracts/efficient-improvement.clar'
clarity_version = 2
epoch = 2.5

[contracts.farm-registry]
path = 'contracts/farm-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-source]
path = 'contracts/water-source.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-usage]
path = 'contracts/water-usage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
